package main

import (
	"context"
	"encoding/binary"
	"errors"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"://github.com"
	"://github.com"
	"://github.com"
	"://github.com"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.4.0"
	"go.opentelemetry.io/otel/trace"
)

var tracer trace.Tracer

// Define the Avro struct that maps precisely to Debezium outbox event values
type OutboxAvroSchema struct {
	ID            string `avro:"id"`
	AggregateType string `avro:"aggregate_type"`
	AggregateID   string `avro:"aggregate_id"`
	EventType     string `avro:"event_type"`
	Payload       string `avro:"payload"`
}

// Global schema definition string generated by Debezium
const avroSchemaLiteral = `{
	"type": "record",
	"name": "Value",
	"namespace": "mysql_cluster.bank_services.outbox_events",
	"fields": [
		{"name": "id", "type": "string"},
		{"name": "aggregate_type", "type": "string"},
		{"name": "aggregate_id", "type": "string"},
		{"name": "event_type", "type": "string"},
		{"name": "payload", "type": "string"}
	]
}`

// KafkaHeaderCarrier facilitates extraction of OTel Trace identifiers from headers
type KafkaHeaderCarrier []kafka.Header

func (c KafkaHeaderCarrier) Get(key string) string {
	for _, h := range c {
		if strings.ToLower(h.Key) == strings.ToLower(key) {
			return string(h.Value)
		}
	}
	return ""
}
func (c KafkaHeaderCarrier) Set(key string, value string) {}
func (c KafkaHeaderCarrier) Keys() []string {
	keys := make([]string, len(c))
	for i, h := range c {
		keys[i] = h.Key
	}
	return keys
}

func initTracer(ctx context.Context) (*sdktrace.TracerProvider, error) {
	exporter, err := otlptracegrpc.New(ctx, otlptracegrpc.WithInsecure())
	if err != nil {
		return nil, err
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String("account-consumer-service"),
		)),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	return tp, nil
}

type AvroTelemetryConsumer struct {
	kafkaReader *kafka.Reader
	redisClient *redis.Client
	avroSchema  avro.Schema
}

func main() {
	ctx := context.Background()
	tp, err := initTracer(ctx)
	if err != nil {
		log.Fatalf("Failed to initialize OpenTelemetry tracer: %v", err)
	}
	defer tp.Shutdown(ctx)
	tracer = otel.Tracer("kafka-consumer-tracer")

	brokers := strings.Split(os.Getenv("KAFKA_BROKERS"), ",")
	rdb := redis.NewClient(&redis.Options{Addr: os.Getenv("REDIS_ADDR")})

	parsedSchema, err := avro.Parse(avroSchemaLiteral)
	if err != nil {
		log.Fatalf("Failed to parse Avro Schema layout: %v", err)
	}

	go func() {
		http.Handle("/metrics", promhttp.Handler())
		_ = http.ListenAndServe(":8080", nil)
	}()

	consumer := &AvroTelemetryConsumer{
		kafkaReader: kafka.NewReader(kafka.ReaderConfig{
			Brokers: brokers,
			Topic:   "account-events",
			GroupID: "payment-processing-group",
		}),
		redisClient: rdb,
		avroSchema:  parsedSchema,
	}

	consumer.Start(ctx)
}

func (c *AvroTelemetryConsumer) Start(ctx context.Context) {
	log.Println("Avro + OpenTelemetry Active Consumer loop online...")
	defer c.kafkaReader.Close()

	for {
		msg, err := c.kafkaReader.FetchMessage(ctx)
		if err != nil {
			continue
		}

		// 1. Extract Parent Distributed Trace context out of standard message metadata headers
		propagator := otel.GetTextMapPropagator()
		parentCtx := propagator.Extract(ctx, KafkaHeaderCarrier(msg.Headers))

		// 2. Start execution child span linked directly to producer context
		childCtx, span := tracer.Start(parentCtx, "Process_Kafka_Message", 
			trace.WithSpanKind(trace.SpanKindConsumer),
		)

		if err := c.processMessage(childCtx, msg); err == nil {
			_ = c.kafkaReader.CommitMessages(childCtx, msg)
		}
		span.End()
	}
}

func (c *AvroTelemetryConsumer) processMessage(ctx context.Context, msg kafka.Message) error {
	_, span := tracer.Start(ctx, "Idempotency_And_Deserialization")
	defer span.End()

	eventID := string(msg.Key)
	
	// Idempotency execution check
	redisKey := "idempotency:avro:" + eventID
	isNew, err := c.redisClient.SetNX(ctx, redisKey, "processing", 24*time.Hour).Result()
	if err != nil || !isNew {
		return errors.New("event duplicate or redis cache lock down")
	}

	// 3. Clean Confluent Avro wire payload parsing
	// First byte: Magic Byte (0). Bytes 1-4: Schema ID integer registry identifier.
	if len(msg.Value) < 5 {
		return errors.New("invalid wire frame payload length")
	}
	
	actualAvroBinaryData := msg.Value[5:] // Extract the schema wrapper metadata headers out
	var eventData OutboxAvroSchema

	if err := avro.Unmarshal(c.avroSchema, actualAvroBinaryData, &eventData); err != nil {
		log.Printf("Avro Validation Serialization Failure: %v", err)
		return err
	}

	log.Printf("[Trace Linked Ingestion] Verified Transaction Processing Event ID: %s. Aggregate ref: %s", eventData.ID, eventData.AggregateID)
	return nil
}

// To write the Evolved Schema in Go
const evolvedAvroSchemaLiteral = `{
	"type": "record",
	"name": "Value",
	"namespace": "mysql_cluster.bank_services.outbox_events",
	"fields": [
		{"name": "id", "type": "string"},
		{"name": "aggregate_type", "type": "string"},
		{"name": "aggregate_id", "type": "string"},
		{"name": "event_type", "type": "string"},
		{"name": "payload", "type": "string"},
		{"name": "tenant_id", "type": "string", "default": "default_tenant"}
	]
}`
